/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import classes.Car;
import classes.User;
import java.awt.Color;
import java.awt.Cursor;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JEditorPane;
import javax.swing.JFrame;
import run.Sqlite;

/**
 *
 * @author Joen
 */
public class carModelDisplay extends javax.swing.JFrame {

    String background = "";
    public static JFrame FRAME2;
    classes.User newUser = new User("", 0);
    classes.Car newCar = new Car("", "", "", "", 0, 0);
    Car mercedesAclass = new Car("Mercedes", "A class", "A180 CDI", "Diesel", 2017, 10000);
    Car mercedesCclass = new Car("Mercedes", "C class", "C 200D", "Diesel", 2017, 20000);
    Car mercedesEclass = new Car("Mercedes", "E class", "E 220D", "Diesel", 2017, 30000);
    Car mercedesSclass = new Car("Mercedes", "S class", "S 350D", "Diesel", 2017, 40000);
    Car BMWmodel1 = new Car("BMW", "Model 1", "TwinPower Turbo", "Diesel", 2017, 10000);
    Car BMWmodel3 = new Car("BMW", "Model 3", "TwinPower Turbo", "Diesel", 2017, 20000);
    Car BMWmodel5 = new Car("BMW", "Model 5", "TwinPower Turbo", "Diesel", 2017, 30000);
    Car BMWmodel7 = new Car("BMW", "Model 7", "TwinPower Turbo", "Diesel", 2017, 40000);
    Car volvoS60 = new Car("Volvo", "S60", "D2", "Diesel", 2017, 10000);
    Car volvoV40 = new Car("Volvo", "V40", "D2", "Diesel", 2017, 20000);
    Car volvoS90 = new Car("Volvo", "S90", "D4", "Diesel", 2017, 30000);
    Car volvoXC90 = new Car("Volvo", "XC90", "D5 PowerPulse", "Diesel", 2017, 40000);

    /**
     * Creates new form Mercedes
     *
     * @param user1
     * @param car1
     */
    public carModelDisplay(User user1, Car car1) {
        newUser = user1;
        newCar = car1;
        initComponents();
        doThisAtStart();
    }

    private void doThisAtStart() {
        checkBackgroundColor();
        findModels();
        jTextArea1.setEditable(false);
        jTextArea2.setEditable(false);
        jTextArea3.setEditable(false);
        jTextArea4.setEditable(false);
        carModelLabel1.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        carModelLabel2.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        carModelLabel3.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        carModelLabel4.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        carModelLabel1 = new javax.swing.JLabel();
        carModelLabel2 = new javax.swing.JLabel();
        carModelLabel3 = new javax.swing.JLabel();
        carModelLabel4 = new javax.swing.JLabel();
        jTextArea1 = new javax.swing.JTextArea();
        jTextArea4 = new javax.swing.JTextArea();
        jTextArea3 = new javax.swing.JTextArea();
        jTextArea2 = new javax.swing.JTextArea();
        descriptionLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 200));
        setResizable(false);
        setSize(new java.awt.Dimension(720, 460));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(95, 166, 190));
        jPanel1.setPreferredSize(new java.awt.Dimension(720, 440));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setFocusable(false);
        jTextArea1.setRequestFocusEnabled(false);

        jTextArea4.setColumns(20);
        jTextArea4.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jTextArea4.setRows(5);
        jTextArea4.setFocusable(false);

        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jTextArea3.setRows(5);
        jTextArea3.setBorder(null);
        jTextArea3.setFocusable(false);

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setFocusable(false);

        descriptionLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        descriptionLabel.setText("Click on a vehicle to proceed...");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(carModelLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextArea3, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(carModelLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(carModelLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextArea4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(carModelLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextArea2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(289, 289, 289)
                        .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(descriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(jTextArea2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(carModelLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(carModelLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(carModelLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carModelLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextArea3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextArea4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(descriptionLabel)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 470));

        jMenu1.setBackground(new java.awt.Color(204, 204, 204));
        jMenu1.setText("System");

        jMenuItem1.setBackground(new java.awt.Color(204, 204, 204));
        jMenuItem1.setText("Main Menu");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        FRAME2 = new FirstPage(newUser);
        FRAME2.setVisible(true);
        disposeThisWindow();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(carModelDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(carModelDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(carModelDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(carModelDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new carModelDisplay(new User("", 0), new Car("", "", "", "", 0, 0)).setVisible(true);
        });
    }

    private void checkBackgroundColor() {

        String color = "";
        Connection conn = null;
        try {
            conn = (new Sqlite().connect());

            String SQL = "Select * from options WHERE user_id =" + newUser.getId();
            try (ResultSet rs = conn.createStatement().executeQuery(SQL)) {
                while (rs.next()) {
                    color = rs.getString(3);
                }
                conn.close();
            }

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(FirstPage.class.getName()).log(Level.SEVERE, null, ex);
        }

        switch (color) {
            case "Blue":
                jPanel1.setBackground(new Color(90, 166, 190));
                jTextArea1.setBackground(new Color(90, 166, 190));
                jTextArea2.setBackground(new Color(90, 166, 190));
                jTextArea3.setBackground(new Color(90, 166, 190));
                jTextArea4.setBackground(new Color(90, 166, 190));
                break;
            case "Grey":
                jPanel1.setBackground(Color.gray);
                jTextArea1.setBackground(Color.gray);
                jTextArea2.setBackground(Color.gray);
                jTextArea3.setBackground(Color.gray);
                jTextArea4.setBackground(Color.gray);
                break;
            case "Red":
                jPanel1.setBackground(Color.red);
                jTextArea1.setBackground(Color.red);
                jTextArea2.setBackground(Color.red);
                jTextArea3.setBackground(Color.red);
                jTextArea4.setBackground(Color.red);
                break;
            default:
                jPanel1.setBackground(new Color(90, 166, 190));
                break;
        }

        background = color;
    }

    void disposeThisWindow() {
        FirstPage.FRAME2.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel carModelLabel1;
    private javax.swing.JLabel carModelLabel2;
    private javax.swing.JLabel carModelLabel3;
    private javax.swing.JLabel carModelLabel4;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JLabel logoLabel;
    // End of variables declaration//GEN-END:variables

    private void findModels() {
        //MERCEDES MODELS SECTION
        if (newCar.getMake().equals("Mercedes")) {
            logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rsz_mercedes_icon.png")));
            carModelLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rsz_mercedes_aclass_image.png")));
            carModelLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rsz_mercedes_cclass_image.png")));
            carModelLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rsz_mercedes_eclass_image.png")));
            carModelLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rsz_mercedes_sclass_image.png")));
            jTextArea1.setText("Make: " + volvoV40.getMake() + "\nModel: "
                    + mercedesAclass.getModel() + "\nEngine: " + mercedesAclass.getEngine() + "\nFuel: "
                    + mercedesAclass.getFuel() + "\nYear: " + mercedesAclass.getYear() + "\nCost: " + mercedesAclass.getCost());
            jTextArea2.setText("Make: " + mercedesAclass.getMake() + "\nModel: "
                    + mercedesCclass.getModel() + "\nEngine: " + mercedesCclass.getEngine() + "\nFuel: "
                    + mercedesCclass.getFuel() + "\nYear: " + mercedesCclass.getYear() + "\nCost: " + mercedesCclass.getCost());
            jTextArea3.setText("Make: " + mercedesAclass.getMake() + "\nModel: "
                    + mercedesEclass.getModel() + "\nEngine: " + mercedesEclass.getEngine() + "\nFuel: "
                    + mercedesEclass.getFuel() + "\nYear: " + mercedesEclass.getYear() + "\nCost: " + mercedesEclass.getCost());
            jTextArea4.setText("Make: " + mercedesAclass.getMake() + "\nModel: "
                    + mercedesSclass.getModel() + "\nEngine: " + mercedesSclass.getEngine() + "\nFuel: "
                    + mercedesSclass.getFuel() + "\nYear: " + mercedesSclass.getYear() + "\nCost: " + mercedesSclass.getCost());
        } //END OF MERCEDES MODELS SECTION
        //BMW MODELS SECTION
        else if (newCar.getMake().equals("BMW")) {
            logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rsz_bmw_icon.png")));
            carModelLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rsz_bmw_model1.png")));
            carModelLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rsz_bmw_model3.png")));
            carModelLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rsz_bmw_model5.png")));
            carModelLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rsz_bmw_model7.png")));
            jTextArea1.setText("Make: " + BMWmodel1.getMake() + "\nModel: "
                    + BMWmodel1.getModel() + "\nEngine: " + BMWmodel1.getEngine() + "\nFuel: "
                    + BMWmodel1.getFuel() + "\nYear: " + BMWmodel1.getYear() + "\nCost: " + BMWmodel1.getCost());
            jTextArea2.setText("Make: " + BMWmodel1.getMake() + "\nModel: "
                    + BMWmodel3.getModel() + "\nEngine: " + BMWmodel3.getEngine() + "\nFuel: "
                    + BMWmodel3.getFuel() + "\nYear: " + BMWmodel3.getYear() + "\nCost: " + BMWmodel3.getCost());
            jTextArea3.setText("Make: " + BMWmodel5.getMake() + "\nModel: "
                    + BMWmodel5.getModel() + "\nEngine: " + BMWmodel5.getEngine() + "\nFuel: "
                    + BMWmodel5.getFuel() + "\nYear: " + BMWmodel5.getYear() + "\nCost: " + BMWmodel5.getCost());
            jTextArea4.setText("Make: " + BMWmodel7.getMake() + "\nModel: "
                    + BMWmodel7.getModel() + "\nEngine: " + BMWmodel7.getEngine() + "\nFuel: "
                    + BMWmodel7.getFuel() + "\nYear: " + BMWmodel7.getYear() + "\nCost: " + BMWmodel7.getCost());
        }//END OF BMW MODELS SECTION
        //VOLVO MODELS SECTION
        else if (newCar.getMake().equals("Volvo")) {
            logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rsz_volvo_icon.png")));
            carModelLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rsz_volvo_v40.png")));
            carModelLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rsz_volvo_s60.png")));
            carModelLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rsz_volvo_s90.png")));
            carModelLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rsz_volvo_xc90.png")));
            jTextArea1.setText("Make: " + volvoV40.getMake() + "\nModel: "
                    + volvoV40.getModel() + "\nEngine: " + volvoV40.getEngine() + "\nFuel: "
                    + volvoV40.getFuel() + "\nYear: " + volvoV40.getYear() + "\nCost: " + volvoV40.getCost());
            jTextArea2.setText("Make: " + volvoS60.getMake() + "\nModel: "
                    + volvoS60.getModel() + "\nEngine: " + volvoS60.getEngine() + "\nFuel: "
                    + volvoS60.getFuel() + "\nYear: " + volvoS60.getYear() + "\nCost: " + volvoS60.getCost());
            jTextArea3.setText("Make: " + volvoS90.getMake() + "\nModel: "
                    + volvoS90.getModel() + "\nEngine: " + volvoS90.getEngine() + "\nFuel: "
                    + volvoS90.getFuel() + "\nYear: " + volvoS90.getYear() + "\nCost: " + volvoS90.getCost());
            jTextArea4.setText("Make: " + volvoXC90.getMake() + "\nModel: "
                    + volvoXC90.getModel() + "\nEngine: " + volvoXC90.getEngine() + "\nFuel: "
                    + volvoXC90.getFuel() + "\nYear: " + volvoXC90.getYear() + "\nCost: " + volvoXC90.getCost());
        } //END OF VOLVO MODELS SECTION
        else if (newCar.getMake().equals("Volkswagen")) {
            logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rsz_volkswagen_icon.png")));
        } else if (newCar.getMake().equals("Porsche")) {
            logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rsz_porsche_icon.png")));
        } else if (newCar.getMake().equals("Jaguar")) {
            logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rsz_jaguar_icon.png")));
        }
    }

}
